# Assignment Set 2 - Data Manipulation I

#### ***Solved by - Himel Sarder***
#### ***gmail : info.himelcse@gmail.com***

In [1]:
import numpy as np

### 1. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10. 

In [2]:
# Create a 2D array of shape 5x3 with random decimal numbers between 5 and 10
random_array = np.random.uniform(5, 10, (5, 3))

# Display the array
print("Generated 2D Array:")
print(random_array)

Generated 2D Array:
[[5.92930247 9.49843278 8.6826846 ]
 [7.41517886 7.86206007 7.55700242]
 [9.8235138  8.06484717 7.35661734]
 [5.26575683 7.12448375 8.27970514]
 [7.81233489 9.05939365 8.48212914]]


### 2. Insert np.nan values at 20 random positions in iris_2d dataset

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```



In [6]:
# Load the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Get the total number of elements in the dataset
total_elements = iris_2d.size
print(total_elements)

# Generate 20 random indices
random_indices = np.random.choice(total_elements, size=20, replace=False)
print(random_indices)

# Insert np.nan at the selected positions
iris_2d.ravel()[random_indices] = np.nan

# Print the modified dataset
print(iris_2d)

600
[324 341 155 448 323 307 340 422 173 561 298 362 230 158 276 194 118 429
 332 449]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 nan]
 [5.1 3.4 nan 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  nan 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 

### 3.  Find out if iris_2d has any missing values

``` 
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
````


In [7]:
# Load the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Check if there are any missing values (NaN) in the dataset
has_missing_values = np.isnan(iris_2d).any()

# Print the result
print("Does the dataset have missing values?", has_missing_values)

Does the dataset have missing values? False


### 4.  Find the number and position of missing values in iris_2d's sepallength (1st column)

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

````


In [8]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 7
Position of missing values: 
 (array([ 11,  71,  96, 104, 108, 116, 123], dtype=int64),)


### 5. Select the rows of iris_2d that does not have any nan value.

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

```

In [9]:
# Load the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Insert random NaN values (for demonstration)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Select rows that do not have any NaN values
rows_without_nan = iris_2d[~np.isnan(iris_2d).any(axis=1)]

# Print the result
print("Rows without any NaN values:")
print(rows_without_nan)

Rows without any NaN values:
[[4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [4.9 2.4 3.3 1. ]
 [

### 6. Find mean of every row in iris_2d array

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

````

In [10]:
# Load the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')

# Insert random NaN values (for demonstration)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Calculate the mean of every row, ignoring NaN values
row_means = np.nanmean(iris_2d, axis=1)

# Print the result
print("Mean of every row in iris_2d (ignoring NaN values):")
print(row_means)

Mean of every row in iris_2d (ignoring NaN values):
[2.55       2.375      2.35       2.35       2.55       2.85
 2.425      2.525      2.225      2.4        2.7        2.5
 2.1        2.125      2.8        3.         2.75       2.575
 3.73333333 2.675      2.675      2.675      2.35       2.65
 2.575      2.45       2.6        2.3        2.55       2.425
 2.425      2.675      2.725      2.825      2.4        2.13333333
 2.625      2.4        2.225      2.55       2.525      2.1
 2.275      2.675      2.8        2.375      2.675      2.35
 2.675      2.475      4.075      3.9        4.1        3.275
 3.85       3.575      3.975      3.06666667 3.85       3.3
 2.875      3.65       3.3        3.775      3.35       3.9
 3.65       3.4        4.06666667 3.06666667 3.26666667 3.55
 3.8        3.7        3.725      3.85       3.95       4.1
 3.725      3.2        3.2        3.4        3.4        3.85
 3.6        3.875      4.         3.575      3.5        3.325
 3.425      3.775      3.4  

### 7. Get the common items between a and b

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### 8. From array a remove all items present in array b

```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

In [12]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])